version: "3.5"

services:
  rstudio-workbench:
    container_name: rstudio-workbench
    build:
      context: ./workbench
      args:
        RSW_VERSION: 2022.02.3+492.pro3
    image: rstudio/rstudio-workbench:2022.02.3-492.pro3
    privileged: true
    environment:
      RSW_LICENSE: ${RSW_LICENSE}
      LICENSE_SERVER: ${RSW_LICENSE_SERVER}
    ports:
      - 8787:8787
      - 5559:5559
    volumes:
      - ./workbench/conf/:/etc/rstudio
      - ./data/rsw:/home

  rstudio-connect:
    container_name: rstudio-connect
    build:
      context: ./connect
      args:
        RSC_VERSION: 2022.05.0
    image: rstudio/rstudio-connect:2022.05.0
    privileged: true
    environment:
      RSC_LICENSE: ${RSC_LICENSE}
      LICENSE_SERVER: ${RSC_LICENSE_SERVER}
    ports:
      - 3939:3939
    volumes:
      - ./connect/rstudio-connect.gcfg:/etc/rstudio-connect/rstudio-connect.gcfg
      - ./data/rsc:/data

  rstudio-package-manager:
    container_name: rstudio-package-manager
    build:
      context: ./package-manager
      args:
        RSPM_VERSION: 2022.04.0-7
    image: rstudio/rstudio-package-manager:2022.04.0-7
    privileged: true
    environment:
      RSPM_LICENSE: ${RSPM_LICENSE}
      LICENSE_SERVER: ${RSPM_LICENSE_SERVER}
    ports:
      - 4242:4242
    volumes:
      - ./package-manager/rstudio-pm.gcfg:/etc/rstudio-pm/rstudio-pm.gcfg
      - ./data/rspm:/data
