version: "3.5"

services:
  workbench:
    container_name: rstudio-workbench
    image: rstudio/rstudio-workbench:${RSW_VERSION:-ubuntu2204}
    environment:
      RSW_LICENSE: ${RSW_LICENSE}
      LICENSE_SERVER: ${RSW_LICENSE_SERVER}
    ports:
      - "8787:8787"
      - "5559:5559"
    volumes:
      - ./workbench/conf/:/etc/rstudio
      - ./data/rsw:/home

  connect:
    container_name: rstudio-connect
    image: rstudio/rstudio-connect:${RSC_VERSION:-ubuntu2204}
    privileged: true
    environment:
      RSC_LICENSE: ${RSC_LICENSE}
      LICENSE_SERVER: ${RSC_LICENSE_SERVER}
    ports:
      - "3939:3939"
    volumes:
      - ./connect/rstudio-connect.gcfg:/etc/rstudio-connect/rstudio-connect.gcfg
      - ./data/rsc:/data

  package-manager:
    container_name: rstudio-package-manager
    image: rstudio/rstudio-package-manager:${RSPM_VERSION:-ubuntu2204}
    environment:
      RSPM_LICENSE: ${RSPM_LICENSE}
      LICENSE_SERVER: ${RSPM_LICENSE_SERVER}
    ports:
      - "4242:4242"
    volumes:
      - ./package-manager/rstudio-pm.gcfg:/etc/rstudio-pm/rstudio-pm.gcfg
      - ./data/rspm:/data
