version: '2.3'
services:

  sut:
    image: $IMAGE_NAME
    command: /run_tests.sh
    entrypoint: []
    environment:
      # uses .env by default
      - RSC_VERSION
    volumes:
      - "./test/run_tests.sh:/run_tests.sh"
      - "./test/goss.yaml:/tmp/goss.yaml"
