on:
  schedule:
    - cron: "0 8 * * 1"
  push:
    branches:
      - gcw-workbench

name: Build Workbench for Google Cloud Workstations
jobs:
  build-workbench-for-gcw:
    runs-on: ubuntu-latest
    env:
      R_VERSION: 4.2.2
      R_VERSION_ALT: 4.1.3
      PYTHON_VERSION: 3.10.10
      PYTHON_VERSION_ALT: 3.9.16
      RSW_VERSION: 2023.05.0-daily-271.pro3
      RSW_DOWNLOAD_URL: https://s3.amazonaws.com/rstudio-ide-build/server/bionic/amd64

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3
        with:
          ref: gcw-workbench

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_ARTIFACT_REGISTRY_JSON }}'

      - name: Set up Just
        uses: extractions/setup-just@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

#      - name: Get Version
#        id: get-version
#        run: |
#          VERSION=`just -f ci.Justfile get-version workbench --type=release --local`
#          VERSION=${VERSION//\"/}
#          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
#          echo "TAG_SAFE_VERSION=${VERSION/+/-}" >> $GITHUB_OUTPUT

      - name: Build base image
        id: build
        run: |
          TAGS=$(just \
            BUILDX_PATH=${{ steps.buildx.outputs.name }} \
            RSW_VERSION=${{ env.RSW_VERSION }} \
            RSW_DOWNLOAD_URL=${{ env.RSW_DOWNLOAD_URL }} \
            R_VERSION=${{ env.R_VERSION }} \
            R_VERSION_ALT=${{ env.R_VERSION_ALT }} \
            PYTHON_VERSION=${{ env.PYTHON_VERSION }} \
            PYTHON_VERSION_ALT=${{ env.PYTHON_VERSION_ALT }} \
            PYTHON_VERSION_JUPYTER=${{ env.PYTHON_VERSION }} \
            workbench-for-google-cloud-workstations/build \
            us-central1-docker.pkg.dev/gcp-workstations-testing/posit/workbench-for-gcw:latest \
            us-central1-docker.pkg.dev/gcp-workstations-testing/posit/workbench-for-gcw:${{ env.RSW_VERSION }})
          echo "TAGS=$TAGS" >> $GITHUB_OUTPUT

      - name: Test Image
        run: |
          IFS=" " read -a tags <<<"${{ steps.build.outputs.TAGS }}"
          just \
            RSW_VERSION=${{ env.RSW_VERSION }} \
            R_VERSION=${{ env.R_VERSION }} \
            R_VERSION_ALT=${{ env.R_VERSION_ALT }} \
            PYTHON_VERSION=${{ env.PYTHON_VERSION }} \
            PYTHON_VERSION_ALT=${{ env.PYTHON_VERSION_ALT }} \
            PYTHON_VERSION_JUPYTER=${{ env.PYTHON_VERSION }} \
            workbench-for-google-cloud-workstations/test "${tags[1]}"

      - name: Authenticate GCAR
        run: |
          gcloud auth configure-docker -q us-central1-docker.pkg.dev
          
      - name: Push Image
        run: docker push ${{ steps.build.outputs.TAGS }}
