on:
  schedule:
    - cron: "0 8 * * 1"
  push:
    branches:
      - gcw-workbench
      - main
      - dev

name: Build Workbench for Google Cloud Workstations
jobs:
  build-workbench-for-gcw:
    runs-on: ubuntu-latest
    env:
      DOTENV_FILE: ./workbench-for-google-cloud-workstations/.env

    steps:

      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Set environment variables using .env file
        run: cat ${{ env.DOTENV_FILE }} >> "$GITHUB_ENV"

      - name: Set up Just
        uses: extractions/setup-just@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_ARTIFACT_REGISTRY_JSON }}'

      - name: Authenticate GCAR
        run: |
          gcloud auth configure-docker -q us-central1-docker.pkg.dev

      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: ./workbench-for-google-cloud-workstations
          load: true
          cache-from: type=gha
          cache-to: type=gha
          build-args: |
            RSW_VERSION=${{ env.RSW_VERSION }}
            R_VERSION=${{ env.R_VERSION }}
            R_VERSION_ALT=${{ env.R_VERSION_ALT }}
            PYTHON_VERSION=${{ env.PYTHON_VERSION }}
            PYTHON_VERSION_ALT=${{ env.PYTHON_VERSION_ALT }}
            PYTHON_VERSION_JUPYTER=${{ env.PYTHON_VERSION }}
            DRIVERS_VERSION=${{ env.DRIVERS_VERSION }}
            RSW_DOWNLOAD_URL=${{ env.RSW_DOWNLOAD_URL }}
          tags: |
            ${{ env.IMAGE_REGISTRY_NAME }}:latest
            ${{ env.IMAGE_REGISTRY_NAME }}:${{ env.RSW_TAG_VERSION }}

      - name: Test Image
        run: |
          just workbench-for-google-cloud-workstations/test ${{ env.IMAGE_REGISTRY_NAME }}:${{ env.RSW_TAG_VERSION }}

      - name: Push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: workbench-for-google-cloud-workstations
          cache-from: type=gha
          cache-to: type=gha
          build-args: |
            RSW_VERSION=${{ env.RSW_VERSION }}
            R_VERSION=${{ env.R_VERSION }}
            R_VERSION_ALT=${{ env.R_VERSION_ALT }}
            PYTHON_VERSION=${{ env.PYTHON_VERSION }}
            PYTHON_VERSION_ALT=${{ env.PYTHON_VERSION_ALT }}
            PYTHON_VERSION_JUPYTER=${{ env.PYTHON_VERSION }}
            DRIVERS_VERSION=${{ env.DRIVERS_VERSION }}
            RSW_DOWNLOAD_URL=${{ env.RSW_DOWNLOAD_URL }}
          tags: |
            ${{ env.IMAGE_REGISTRY_NAME }}:latest
            ${{ env.IMAGE_REGISTRY_NAME }}:${{ env.RSW_TAG_VERSION }}
