on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: RStudio Content Base
jobs:

  build:
    runs-on: ubuntu-latest
    name: r${{ matrix.config.r }} py${{ matrix.config.py }} ${{ matrix.config.os }} ${{ github.ref }}

    # this is copied below
    strategy:
      fail-fast: false
      matrix:
        config:
          # at least one image containing the older versions
          - {r: '3.1.3', py: '2.7.18', os: 'bionic'}
          - {r: '3.2.5', py: '2.7.18', os: 'bionic'}
          - {r: '3.3.3', py: '3.6.13', os: 'bionic'}
          - {r: '3.4.4', py: '3.6.13', os: 'bionic'}
          - {r: '3.5.3', py: '3.7.10', os: 'bionic'}
          - {r: '3.6.3', py: '3.8.8', os: 'bionic'}
          # latest two R/Python are built with both sets of combinations
          - {r: '4.0.5', py: '3.8.8', os: 'bionic'}
          - {r: '4.0.5', py: '3.9.2', os: 'bionic'}
          - {r: '4.1.0', py: '3.8.8', os: 'bionic'}
          - {r: '4.1.0', py: '3.9.2', os: 'bionic'}

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./content-base/${{ matrix.config.os }}
          file: ./content-base/${{ matrix.config.os }}/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          tags: |
            rstudio/content-base:r${{ matrix.config.r }}-py${{ matrix.config.py }}-${{ matrix.config.os }}
            ghcr.io/rstudio/content-base:r${{ matrix.config.r }}-py${{ matrix.config.py }}-${{ matrix.config.os }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          outputs: type=docker,dest=/tmp/r${{ matrix.config.r }}-py${{ matrix.config.py }}-${{ matrix.config.os }}-image.tar
          build-args: |
            R_VERSION=${{ matrix.config.r }}
            PYTHON_VERSION=${{ matrix.config.py }}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: r${{ matrix.config.r }}-py${{ matrix.config.py }}-${{ matrix.config.os }}-image
          path: /tmp/r${{ matrix.config.r }}-py${{ matrix.config.py }}-${{ matrix.config.os }}-image.tar

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  push:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref == 'refs/heads/main' }}
    name: push-r${{ matrix.config.r }}-py${{ matrix.config.py }}-${{ matrix.config.os }} ${{ github.ref }}
    environment: build-and-push

    # this is copied below
    strategy:
      fail-fast: false
      matrix:
        config:
          # at least one image containing the older versions
          - {r: '3.1.3', py: '2.7.18', os: 'bionic'}
          - {r: '3.2.5', py: '2.7.18', os: 'bionic'}
          - {r: '3.3.3', py: '3.6.13', os: 'bionic'}
          - {r: '3.4.4', py: '3.6.13', os: 'bionic'}
          - {r: '3.5.3', py: '3.7.10', os: 'bionic'}
          - {r: '3.6.3', py: '3.8.8', os: 'bionic'}
          # latest two R/Python are built with both sets of combinations
          - {r: '4.0.5', py: '3.8.8', os: 'bionic'}
          - {r: '4.0.5', py: '3.9.2', os: 'bionic'}
          - {r: '4.1.0', py: '3.8.8', os: 'bionic'}
          - {r: '4.1.0', py: '3.9.2', os: 'bionic'}

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: r${{ matrix.config.r }}-py${{ matrix.config.py }}-${{ matrix.config.os }}-image
          path: /tmp

      - name: Load image
        run: |
          docker load --input /tmp/r${{ matrix.config.r }}-py${{ matrix.config.py }}-${{ matrix.config.os }}-image.tar
          docker image ls -a

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.BUILD_PAT }}

      - name: Push image(s)
        run: |
          docker push rstudio/content-base:r${{ matrix.config.r }}-py${{ matrix.config.py }}-${{ matrix.config.os }}
          docker push ghcr.io/rstudio/content-base:r${{ matrix.config.r }}-py${{ matrix.config.py }}-${{ matrix.config.os }}
