on:
  schedule:
    - cron: "0 8 * * 1"
  push:
    branches:
      - gcw-workbench
      - main
      - dev

name: Build Workbench for Google Cloud Workstations
jobs:
  build-workbench-for-gcw:
    runs-on: ubuntu-latest
    env:
      R_VERSION: 4.2.3
      R_VERSION_ALT: 4.1.3
      PYTHON_VERSION: 3.10.11
      PYTHON_VERSION_ALT: 3.9.16
      RSW_VERSION: 2023.06.0+421.pro1
      RSW_TAG_VERSION: 2023.06.0-421.pro1
      RSW_DOWNLOAD_URL: https://download2.rstudio.org/server/focal/amd64
      DRIVERS_VERSION: 2023.05.0
      IMAGE_REGISTRY_NAME: us-central1-docker.pkg.dev/posit-images/cloud-workstations/workbench

    steps:

      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Set up Just
        uses: extractions/setup-just@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_ARTIFACT_REGISTRY_JSON }}'

      - name: Authenticate GCAR
        run: |
          gcloud auth configure-docker -q us-central1-docker.pkg.dev

      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: ./workbench-for-google-cloud-workstations
          load: true
          cache-from: type=gha
          cache-to: type=gha
          build-args: |
            RSW_VERSION=${{ env.RSW_VERSION }}
            R_VERSION=${{ env.R_VERSION }}
            R_VERSION_ALT=${{ env.R_VERSION_ALT }}
            PYTHON_VERSION=${{ env.PYTHON_VERSION }}
            PYTHON_VERSION_ALT=${{ env.PYTHON_VERSION_ALT }}
            PYTHON_VERSION_JUPYTER=${{ env.PYTHON_VERSION }}
            DRIVERS_VERSION=${{ env.DRIVERS_VERSION }}
            RSW_DOWNLOAD_URL=${{ env.RSW_DOWNLOAD_URL }}
          tags: |
            ${{ env.IMAGE_REGISTRY_NAME }}:latest
            ${{ env.IMAGE_REGISTRY_NAME }}:${{ env.RSW_TAG_VERSION }}

      - name: Test Image
        run: |
          just \
            RSW_VERSION=${{ env.RSW_VERSION }} \
            R_VERSION=${{ env.R_VERSION }} \
            R_VERSION_ALT=${{ env.R_VERSION_ALT }} \
            PYTHON_VERSION=${{ env.PYTHON_VERSION }} \
            PYTHON_VERSION_ALT=${{ env.PYTHON_VERSION_ALT }} \
            PYTHON_VERSION_JUPYTER=${{ env.PYTHON_VERSION }} \
            DRIVERS_VERSION=${{ env.DRIVERS_VERSION }} \
            workbench-for-google-cloud-workstations/test ${{ env.IMAGE_REGISTRY_NAME }}:${{ env.RSW_TAG_VERSION }}

      - name: Push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: workbench-for-google-cloud-workstations
          cache-from: type=gha
          cache-to: type=gha
          build-args: |
            RSW_VERSION=${{ env.RSW_VERSION }}
            R_VERSION=${{ env.R_VERSION }}
            R_VERSION_ALT=${{ env.R_VERSION_ALT }}
            PYTHON_VERSION=${{ env.PYTHON_VERSION }}
            PYTHON_VERSION_ALT=${{ env.PYTHON_VERSION_ALT }}
            PYTHON_VERSION_JUPYTER=${{ env.PYTHON_VERSION }}
            DRIVERS_VERSION=${{ env.DRIVERS_VERSION }}
            RSW_DOWNLOAD_URL=${{ env.RSW_DOWNLOAD_URL }}
          tags: |
            ${{ env.IMAGE_REGISTRY_NAME }}:latest
            ${{ env.IMAGE_REGISTRY_NAME }}:${{ env.RSW_TAG_VERSION }}
