on:
  push:
    branches:
      - main
      - dev
  pull_request:
  
name: Release - Build, Test, and Push
jobs:
  build:
    name: Build and Test images
    runs-on: ubuntu-latest-4x

    concurrency:
      group: bake-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Just
        uses: extractions/setup-just@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and test
        id: build
        uses: docker/bake-action@v4
        with:
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,compression=zstd
          targets: "build-test"
          push: false

      - name: Test Connect (privileged container)
        run: |
          just -f build.justfile test-connect

      - name: Push
        id: push
        if: github.ref == 'refs/heads/main'
        uses: docker/bake-action@v4
        with:
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,compression=zstd
          targets: "build"
          push: true

  build-content:
    runs-on: ubuntu-latest-4x

    concurrency:
      group: bake-content-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        id: build
        uses: docker/bake-action@v4
        with:
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,compression=zstd
          workdir: content/.
          push: false

      - name: Push
        id: push
        if: github.ref == 'refs/heads/main'
        uses: docker/bake-action@v4
        with:
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,compression=zstd
          workdir: content/.
          push: true
