on:
  push:
    branches:
      - main
      - dev
  pull_request:

name: lint Dockerfiles
jobs:

  lint:
    runs-on: ubuntu-latest
    name: lint-${{ matrix.config.product }}-${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {product: 'product/base', os: 'ubuntu1804'}
          - {product: 'product/base', os: 'ubuntu2204'}
          - {product: 'product/base', os: 'centos7'}
          - {product: 'product/pro', os: 'ubuntu1804'}
          - {product: 'product/pro', os: 'ubuntu2204'}
          - {product: 'product/pro', os: 'centos7'}
          - {product: 'workbench', os: 'ubuntu1804'}
          - {product: 'workbench', os: 'ubuntu2204'}
          - {product: 'connect', os: 'ubuntu1804'}
          - {product: 'connect', os: 'ubuntu2204'}
          - {product: 'connect-content-init', os: 'ubuntu1804'}
          - {product: 'connect-content-init', os: 'ubuntu2204'}
          - {product: 'package-manager', os: 'ubuntu1804'}
          - {product: 'package-manager', os: 'ubuntu2204'}
          - {product: 'r-session-complete', os: 'ubuntu1804'}
          - {product: 'r-session-complete', os: 'centos7'}
          - {product: 'r-session-complete', os: 'ubuntu2204'}
          - {product: 'workbench-for-microsoft-azure-ml', os: 'ubuntu1804'}
          - {product: 'content/base', os: 'ubuntu1804'}
          - {product: 'content/pro', os: 'ubuntu1804'}

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.0.0
        with:
          dockerfile: ${{ matrix.config.product }}/Dockerfile.${{ matrix.config.os }}
          config: ./hadolint.yaml
